export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST" as const;
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS" as const;
export const ORDER_CREATE_FAILURE = "ORDER_CREATE_FAILURE" as const;
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET" as const;

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST" as const;
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS" as const;
export const ORDER_DETAILS_FAILURE = "ORDER_DETAILS_FAILURE" as const;

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST" as const;
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS" as const;
export const ORDER_PAY_FAILURE = "ORDER_PAY_FAILURE" as const;
export const ORDER_PAY_RESET = "ORDER_PAY_RESET" as const;

export const ORDER_HISTORY_REQUEST = "ORDER_HISTORY_REQUEST" as const;
export const ORDER_HISTORY_SUCCESS = "ORDER_HISTORY_SUCCESS" as const;
export const ORDER_HISTORY_FAILURE = "ORDER_HISTORY_FAILURE" as const;
