export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST" as const;
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS" as const;
export const PRODUCT_LIST_FAILURE = "PRODUCT_LIST_FAILURE" as const;

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST" as const;
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS" as const;
export const PRODUCT_DETAILS_FAILURE = "PRODUCT_DETAILS_FAILURE" as const;
