// export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST" as const;
// export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS" as const;
// export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE" as const;

export enum USER_SIGNIN_SIGNOUT {
    SIGNIN_REQUEST = "USER_SIGNIN_REQUEST",
    SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS",
    SIGNIN_FAILURE = "USER_SIGNIN_FAILURE",

    SIGNOUT = "USER_SIGNOUT",
};

export enum USER_SIGNUP {

    SIGNUP_REQUEST = "USER_SIGNUP_REQUEST",
    SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS",
    SIGNUP_FAILURE = "USER_SIGNUP_FAILURE",
}

// export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST" as const;
// export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS" as const;
// export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE" as const;

// export const USER_SIGNOUT = "USER_SIGNOUT" as const;
